### ISSUE TITLE
Can we make Zotra respect the bibtex.el key naming scheme?

### ISSUE THREAD

**Issue by anbanpillay** [mpedramfar/zotra#13]
Thanks for this package. Great work. Works quite well. 

It would be nice if zotra used the key naming scheme set by user for bibtex - this is usually set with bibtex-autokey- variables. Even better, if the key can be used to name the attached file.

**Comment by mpedramfar** [comment]
Isn't this already implemented?
The default settings call `bibtex-clean-entry` which in turn calls `bibtex-generate-autokey` to set bibtex keys. This is done in `zotra-after-get-bibtex-entry-hook`.

**Comment by anbanpillay** [comment]
Thanks for the quick response.
Maybe something in my convoluted dotfile:
This my set up for bibtex:
`(use-package bibtex
  :init
  (setq bibtex-autokey-year-length 4
      bibtex-autokey-name-year-separator ""
      bibtex-autokey-year-title-separator ""
      bibtex-autokey-titleword-separator ""
      bibtex-autokey-titlewords 3
      bibtex-autokey-titlewords-stretch 1
      bibtex-autokey-titleword-length 5)

  :custom
  (bibtex-dialect 'biblatex)
  (bibtex-user-optional-fields
   '(("keywords" "Keywords to describe the entry" "")
     ("file" "Link to document file." ":")))
  (bibtex-align-at-equal-sign t)
  
  (define-key bibtex-mode-map (kbd "H-b") 'org-ref-bibtex-hydra/body))`

and this is the key generated: "artime_origin_2022" - not sure where the "_" is from. The autokey variables are not set anywhere else.  The zotra use-package declaration is standard and from the readme.

But no worries - will investigate further.

**Comment by mpedramfar** [comment]
If you set `zotra-after-get-bibtex-entry-hook` to nil, then you get the raw output. Then, if you run `bibtex-clean-entry` on it, it should change the key according to `bibtex-autokey-*` variables. Is `bibtex-clean-entry` failing? If Zotra sees an error in `bibtex-clean-entry`, it'll just ignore the error and continue.

**Comment by anbanpillay** [comment]
Ok. I tried that - set `zotra-after-get-bibtex-entry-hook` to nil. Then zotra create entry from url. Then run `bibtex-clean-entry` but the key does not change. I created a new entry with bibtex - and when I run `bibtex-clean-entry` is asks to confirm a key - the key was as specified by the `bibtex-autokey-*` variables.

No problem though - the package is perfectly usable.

**Comment by mpedramfar** [comment]
Ok, this could be something about your config, or about limitations of `bibtex-clean-entry`. I'll close this issue for now.
Feel free to reopen if you figured out the issue and it's something that should be fixed here.

**Comment by anbanpillay** [comment]
Great thanks. Will spend more time on checking

**Comment by baracunatana** [comment]
@anbanpillay I was having the same problem and wasn't able to figure out why. Ended up resorting to a bit of brute force and this fixed the problem for me:

```
  (use-package zotra
    :straight
    (:host github :repo "mpedramfar/zotra" :branch "main" :files ("*.el"))

    :custom
    (zotra-default-entry-format "biblatex")
    (zotra-after-get-bibtex-entry-hook '(mimacs/bibtex-clean-entry))

    :config
    (defun mimacs/bibtex-clean-entry ()
      (let ((bibtex-autokey-edit-before-use nil))
        (bibtex-clean-entry t))))

```
It won't ask you to confirm the key.

**Comment by anbanpillay** [comment]
Thank you, will give it a try
