### ISSUE TITLE
Cant find the zotra commands in DOOM?

### ISSUE THREAD

**Issue by ecribia** [mpedramfar/zotra#14]
Hi, Im a very new emacs user (Neovim user actually), so excuse my ignorance.

Ive installed zotra through packages.el with:
(package! zotra)

And for troubleshooting reasons i also installed it via MELPA, but i still cant find the commands when i press M-x

Ive added this to my config.el
(setq zotra-backend 'zotra-server)
(setq zotra-local-server-directory "/home/nocxium/zotra-server/")

which unfortunatly hasnt helped me much. Since i dont know emacs well, and this repo is relatively new, i havent been able to find much information online as well, so im sorry for my beginner question.

Edit: Just to clarify i have also downloaded and installed the zotra-server in the location written in config.el

**Comment by mpedramfar** [comment]
I don't personally use Doom so I'm not quite sure what's happening. Maybe you'd need to `(require 'zotra)` to make it work?

**Comment by ecribia** [comment]
It worked! :+1: Thanks a ton for the help and the awesome package!

**Comment by mpedramfar** [comment]
Perfect!
