### ISSUE TITLE
End of line while parsing JSON error when trying to use the package

### ISSUE THREAD

**Issue by Vidianos-Giannitsis** [mpedramfar/zotra#3]
Hello, I saw this package from your recent post on reddit and I really like the idea of it.

**Error**
I tried setting it up today and I am getting an error when running any of the `zotra-add-entry` functions. Specifically, the error output in the `*Messages*` buffer is
```
(Shell command failed with code 127 and some error output)
/bin/bash: line 1: zotra: command not found

let*: End of file while parsing JSON: "unexpected token near end of file", "<string>", 1, 0, 0
```

**Description of the problem**

I initially tried copying [this](https://www.sciencedirect.com/science/article/pii/S0959652618304360?via%3Dihub) as an example from ScienceDirect and saw that `zotra-add-entry-from-url` already pastes the clipboard to the minibuffer. This gave me the above error. I also tried passing the url as a string (using double-quotes), which in theory should not matter as emacs is reading it with `read-string` but I tested it anyways and it gave the same error. I tried using `zotra-add-entry-from-search` with the article's DOI to see if that worked and got the same error. Lastly, I tried other sites to see if the problem was with ScienceDirect and resulted in that its not that.

**System information to reproduce the error**

I am on the latest version of the package (cloned the repo like 30 mins ago), using Emacs 28.2 and the only code relevant to zotra I have added to my config is
```
(require 'zotra)
(setq zotra-default-bibliography "~/Sync/My_Library2.bib"
      zotra-download-attachment-default-directory "~/Sync/Zotero_pdfs")
```

I can also replicate the error with emacs -Q, by evaluating zotra.el and setting these two variables as its only configuration.

Seeing as this is quite an issue, I am assuming I haven't set something up correctly and its not zotra's fault. But as I have no clue what this is, I thought I should open an issue here in case you have encountered this error before. 

Thanks in advance!
Vidianos

**Comment by mpedramfar** [comment]
Hi! I'm glad you liked it!
Looks like you're using the `zotra-cli` backend. Have you installed `zotra-cli`?

**Comment by Vidianos-Giannitsis** [comment]
Oops, I feel a bit dumb not doing that. I completely forgot I needed to install it separately.

However, it appears that after installing I still get an error. I followed the instructions on the `zotra-cli` github, namely running
```
git clone --recurse-submodules https://github.com/mpedramfar/zotra-cli.git
cd zotra-cli
npm install -g .
```
But after trying to run it I get this error
```
node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module 'config'
Require stack:
- /home/vidianos/Cloned_Repositories/zotra-cli/bin/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/vidianos/Cloned_Repositories/zotra-cli/bin/index.js:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/vidianos/Cloned_Repositories/zotra-cli/bin/index.js' ]
}

Node.js v19.3.0
```
I am on npm v8.19.2 and Node.js v19.3.0 (the latest versions in Arch Linux) although I doubt that is the problem. I've probably forgot something again.

Thanks for helping out!

**Comment by Vidianos-Giannitsis** [comment]
Hmm, I thought I could try and run `sudo npm install` a second time to see if maybe something installed wrongly the first time and weirdly enough it worked. I have no clue what changed between the first and second one, but now zotra seems to be working.

I will close this issue, thanks again.

**Comment by 9s-l-s9** [comment]
I have the same issue. Could the reason be, that you had zotra-cli not globally installed? :( Or do you have any idea, what could have solved your issue? @Vidianos-Giannitsis

**Comment by Vidianos-Giannitsis** [comment]
First issue was fixed by installing zotra-cli. Second issue was fixed by running sudo npm install. However, for some reason, it didn't work the first time and I had to run the command twice.

**Comment by mpedramfar** [comment]
You can also install zotra-cli locally with `npm install` without the `-g` flag and then provide the path to the command by setting
```emacs-lisp
(setq zotra-cli-command '("node" "/full/path/to/zotra-cli/bin/index.js"))
```

**Comment by 9s-l-s9** [comment]
I was able to use zotra, but only with the global install.  I was not able to use the local install, even though I provided `(setq zotra-cli-command '("node" "/full/path/to/zotra-cli/bin/index.js"))` in my config. Thanks.
