### ISSUE TITLE
Using `zotra` to add entry to bibliography + pdf consistently for ArXiV files?

### ISSUE THREAD

**Issue by deen1** [mpedramfar/zotra#5]
I've been trying out `zotra` recently, some very positive things but also some buggy/inconsistent behavior. For papers on the arXiv, I find that doing `zotra-add-entry-from-url` sometimes adds the reference to my chosen `.bib` file, and sometimes doesn't. 

For instance, this resouce, https://arxiv.org/abs/hep-th/0110285 , fails, and in the minibuffer I see this bit of JSON/data:

```
[{"key":"92H6Y6XX","version":0,"itemType":"journalArticle","creators":[{"firstName":"Ian","lastName":"Low","creatorType":"author"},{"firstName":"Aneesh V.","lastName":"Manohar","creatorType":"author"}],"tags":[{"tag":"High Energy Physics - Theory","type":1},{"tag":"Condensed Matter","type":1},{"tag":"High Energy Physics - Phenomenology","type":1}],"title":"Spontaneously Broken Spacetime Symmetries and Goldstone's Theorem","date":"2002-2-25","abstractNote":"Goldstone's theorem states that there is a massless mode for each broken symmetry generator. It has been known for a long time that the naive generalization of this counting fails to give the correct number of massless modes for spontaneously broken spacetime symmetries. We explain how to get the right count of massless modes in the general case, and discuss examples involving spontaneously broken Poincare and conformal invariance.","url":"http://arxiv.org/abs/hep-th/0110285","DOI":"10.1103/PhysRevLett.88.101602","extra":"arXiv:hep-th/0110285","volume":"88","issue":"10","pages":"101602","ISSN":"0031-9007, 1079-7114","publicationTitle":"Physical Review Letters","journalAbbreviation":"Phys. Rev. Lett.","libraryCatalog":"arXiv.org","accessDate":"2023-01-14T15:42:40Z"},{"itemType":"note","parentItem":"92H6Y6XX","note":"Comment: 4 pages; 1 figure; v2: minor corrections. version to appear on PRL"}]
```

`zotra` also does not often download the `pdf` at the same time as the entry for arXiv -- I'm unsure as to why. But it appears to do so on other types of resources -- e.g. APS journal papers, Nature pages. But in these cases the bib file entry does not include a `file={/path/to/file}` field, although my `citar` setup can find the file as it is named the same as the citation key.

Is there some way to get more consistent behavior for `zotra`? Can I set it up to add `file={/path/to/file}` in my bibfile? 

Here is my config:

```
(use-package zotra
  :load-path "~/lisp/zotra"
  :defer t
  :init
  (setq zotra-cli-command "node ~/bin/zotra-cli/bin/index.js")
  :config 
  (setq zotra-download-attachment-default-directory "~/Dropbox/Zotero-storage")
  (setq zotra-default-bibliography "~/org-roam/to-read.bib")
  (add-hook 'zotra-after-add-entry-hook 'org-ref-clean-bibtex-entry)
  ) 
```

I have also included the `zotra-bibtex-completion-get-pdf-url-from-keys` and `bibtex-completion-add-pdf-to-library` functions you suggest on the README.

**Comment by mpedramfar** [comment]
It looks like the issue with the link you sent was the existence of the single quote character in the title. The last commit should solve that issue. Note that I've added a change log section to the README.

As for the second issue, I'm not sure what you mean by that. Without any additional functions, zotra shouldn't download any attachments automatically when you call `zotra-add-entry-from-url`. Could you explain a bit more what exactly you're trying to do?

**Comment by deen1** [comment]
Thanks for your response!

I just did a `git pull` from the `zotra` repo, and reloaded the package to see if your changes worked. 

Just FYI:
I kept getting the error `(wrong-type-argument stringp 110)`  for the arXiv entry mentioned above, as well as for every other paper I tried.  After some playing around I saw you changed

```
  (setq zotra-cli-command "node /path/to/zotra-cli/bin/index.js")
```
to
```
(setq zotra-cli-command '("node" "/path/to/zotra-cli/bin/index.js"))
```

I did that, and got a new error -- turns out you can't use `~/` for `$HOME` but now have to specify the **full path directory** to `zotra-cli`. 

Now your fix appears to work -- papers with apostrophes can be added to my bibliography file. Thanks again!

____________________

For the second issue, I'm afraid I'll still be quite vague, as my config file has gotten fairly complicated after a couple of years of making adjustments. 

Basically, I have recently moved to a `citar` based bibliography/citation setup, and I use `org-ref` and its dependencies  as well.  After I added the above  arXiv paper using `zotra`,  the following shows up in *Messages*:

```
Saving file /home/deen1/org-roam/to-read.bib...
Compiling label environment definitions...done
Wrote /home/deen1/org-roam/to-read.bib
Parsing bibliography file ~/org-roam/to-read.bib ...
Resolving cross-references ...
Done (re)loading bibliography.
doi-utils-async-download-pdf: nil
```

The last line suggests to me that `doi-utils` from `org-ref` has tried and failed to download the arXiv paper from the given URL.

However, if I try the following [Nature News article](https://www.nature.com/articles/d41586-022-04577-5),  I see:

```
Saving file /home/deen1/org-roam/to-read.bib...
Compiling label environment definitions...done
Wrote /home/deen1/org-roam/to-read.bib
Parsing bibliography file ~/org-roam/to-read.bib ...
Resolving cross-references ...
Done (re)loading bibliography.
doi-utils-async-download-pdf: ~/Zotero-storage/kozlov23_disrup_scien_has_declin_no.pdf downloaded
```

And looking for the article on `citar`, I can view the downloaded `pdf`.

I had thought that `zotra-bibtex-completion-get-pdf-url-from-keys` was setup to work with `org-ref` and `doi-utils` to download the `pdf` after the `bibtex` entry was added, but you seem to be suggesting that this is *not* the case -- in which case it is something else in my config that is doing this.

**However, if it is `zotra` that passes on the newly added reference to `doi-utils` to download, is there a way to make sure arXiv papers are consistently automatically downloaded when their entries are added to my bibfile, like the Nature News article was?** 

BTW, thanks very much for your work on this package! If I were more proficient in emacs-lisp I would try to offer up the functionality I wanted as a pull request -- but I'm still very happy with what you've done so far!

**Comment by mpedramfar** [comment]
I see. The issue here is that Zotra doesn't integrate with doi-utils package of org-ref.
I'm not sure if it would be a good idea to integrate them together. If you look into the [source code of doi-utils](https://github.com/jkitchin/org-ref/blob/master/doi-utils.el#L597), you'll see that downloading from 33 sources are supported. It also seems to be using doi, so I'm not sure if it will work if there is no doi associated with the bibtex entry (e.g. in arxiv).
On the other hand, Zotra uses [Zotero translators](https://github.com/zotero/translators) which support about 500 sources and attachments can be downloaded from any of them that have the option of downloading attachments.

The function `zotra-bibtex-completion-get-pdf-url-from-keys` simply returns the url to an attachment for the url field of an entry, which is used in conjugation with `bibtex-completion-add-pdf-to-library`. When you open the helm buffer for an entry and choose "Add PDF to library", now besides the previous options (buffer, file, url), now it also has the option of using Zotra.

If you want to add an entry and download an attachment for it in one go, you can just add this to your config and call it.
```emacs-lisp
(defun zotra-add-entry-from-url-and-download-attachment (url)
  (interactive
   (list (read-string
          "url: "
          (ignore-errors (current-kill 0 t)))))
  (zotra-add-entry-from-url url)
  (zotra-download-attachment-from-url url))
```

**Comment by deen1** [comment]
Sorry for the slow response!

Thanks for your answer, I guessed there would be some issue regarding the lack of `doi`. I honestly don't quite understand how this all works and certainly `org-ref` looks like a very complicated package, so I can imagine there are lots of bells and whistles involved in doing something very simple.

In `org-ref` however, I have found the function `arxiv-get-pdf-add-bibtex-entry` (it's in `org-ref-arxiv.el`), which pretty much replicates the functionality that I want (at least for the arXiv). It has the added benefit (to me) over the nice `zotra-add-entry-from-url-and-download-attachment` function you provided in that it automatically renames the arXiv `.pdf` file to match my citkey, and my `.bib` file is appropriately modified, so that `citar` quickly shows the entry and file. It /doesn't seem/ to use `doi`, it calls `arxiv-get-pdf` which I think just uses a simple substitution of the arXiv ID into a the standard arXiv pdf url.


Maybe that's something you could eventually build into the package if you think its worthwhile? Otherwise, I think I have now set up a workflow where I use:

- The above `org-ref` functions to add arXiv entries to my .bib file and associated `.pdf`s to my library
- `zotra` to add non-arXiv resources to my `.bib` file, and then use `citar-add-file-to-library` to provide a file resource (either a url or an existing file on my system) to a cite key, which `citar` then downloads/copies and renames according the citekey.

**Comment by donlapark** [comment]
Thanks to @deen1's [idea](https://koustuvsinha.com/post/emacs_org_protocol_arxiv/). I have managed to write a hack that uses `zotra` and `org-ref` for downloading pdf and adding `.bib` entry with `file` field. Note that I wrote it with almost zero knowledge in lisp so the code is probably not optimal.

First, I add a "file" protocol to `org-protocol-protocol-alist`
```
(add-to-list 'org-protocol-protocol-alist
             '("file-protocol"
               :protocol "file"
               :function file-protocol))
```
Then I add the following bookmark to my browser.
```
javascript:location.href=('org-protocol://file?url=%27+%20encodeURIComponent(location.href)).replace(/%27/gi,%22%27%22)
```
I also use `org-ref` to clean bibtex entries.
```
(add-hook 'zotra-after-add-entry-hook 'org-ref-clean-bibtex-entry)
```
After that, I write a version of `zotra-add-entry-from-url-and-download-attachment` as suggested above. The idea is the following:
1. use `zotra` to pull a bibtex entry from a website.
2. use `bibtex-parse-entry` to obtain the key.
3. use `zotra` to download the pdf file and rename it to `key.pdf`.
4. use `bibtex-set-field` to write the `file` field in the bibtex entry with the path to `key.pdf` as the value.
```
(setq file_bib "/path/to/bibtex.bib")
(setq file_pdf_loc "/path/to/pdf/folder/")

;; Save pdf to local and maintain a bibfile for the newly added paper
(defun zotra-add-entry-from-url-and-download-attachment (url)
  (interactive
   (list (read-string
          "url: "
          (ignore-errors (current-kill 0 t)))))
  (zotra-add-entry-from-url url)
        (save-window-excursion
                ;; Get the bib file
                (find-file file_bib)
                ;; get to last line
                (goto-char (point-max))
                ;; get to the first line of bibtex
                (bibtex-beginning-of-entry)
                (setq entry (bibtex-parse-entry))
                (setq key (cdr (assoc "=key=" entry)))
                (setq pdf (concat (expand-file-name key file_pdf_loc) ".pdf"))
                (message (concat "checking for key: " key))
                (save-buffer))
  (let* ((url (or url
                  (read-string
                   "url: "
                   (let ((link (org-element-context)))
                     (if (and link
                              (eq (car link) 'link))
                         (org-element-property :raw-link link)
                       (ignore-errors (current-kill 0 t))))))))

  (setq attachments (zotra-get-attachments url))
  (let* ((attachment (if attachments
                         (completing-read
                          "Which attachment to open? "
                          attachments nil t)
                       (user-error "zotra failed to find any attachments in page"))))

    (mkdir (file-name-directory pdf) t)
    (url-copy-file attachment pdf 1)
    (if (zotra-correct-file-extension? pdf)
        pdf
      (delete-file pdf)
      (browse-url attachment)
      (message "The attachment file seems to be corrupted. Opening the attachment in browser..."))
    ))
       (message "Update bibtex with pdf file location")
       (save-window-excursion
                ;; Get the bib file
                (find-file file_bib)
                ;; get to last line
                (goto-char (point-max))
                ;; get to the first line of bibtex
                (bibtex-beginning-of-entry)
                (when (file-exists-p pdf)
                  (bibtex-set-field "file" pdf)
                  (save-buffer)))
)
```
Finally, I write a function that will be triggered when the bookmark is clicked.
```
(defun file-protocol (info)
  (let ((url (plist-get info :url)))
    (message (format "Website: `%s'" url))
    (zotra-add-entry-from-url-and-download-attachment url)
    nil))
```

**Comment by mpedramfar** [comment]
I did some changes to the code, now the function you wrote can be simplified to this:

```emacs-lisp

(defun zotra-add-entry-from-url-and-download-attachment (url)
  (interactive
   (list (read-string
          "url: "
          (ignore-errors (current-kill 0 t)))))
  (let* ((key (zotra-add-entry-from-url url))
         (filename (concat key ".pdf"))
         (filename (zotra-download-attachment-from-url url nil filename)))
    (save-window-excursion
      (bibtex-completion-show-entry (list key))
      (save-restriction
        (bibtex-narrow-to-entry)
        (bibtex-make-field (list "File" nil filename) t))
      (save-buffer))))
```

If you're not using `bibtex-completion`, then `bibtex-completion-show-entry` should be replaced with the appropriate function.

**Comment by mpedramfar** [comment]
I've also added some description to the README for users of bibtex-completion.
I'll close this issue since it seems resolved. Feel free to open an issue if there are problems.

**Comment by deen1** [comment]
Sorry for the late response. I'm still having trouble with downloading the arXiv pdf file when using the `org-protocol` bookmarklet setup, and I've now upgraded to the latest MELPA version.

The reference is added to the bibliography, but your `zotra-add-entry-from-url-and-download-attachment` file [described above](https://github.com/mpedramfar/zotra/issues/5#issuecomment-1565885531) doesn't seem to work.

**Comment by mpedramfar** [comment]
I updated the README with a version of `zotra-add-entry-from-url-and-download-attachment` with a more general solution. Let me know if there are any issues.

**Comment by deen1** [comment]
Thanks! Sorry to keep bugging you about this. I've had some partial success with your new code, and have been trying things out.

The version of `zotra-add-entry-from-url-and-download-attachment` you added works intermittently for me as an interactive function, i.e. when called from Emacs. But it fails for some kinds of arXiv files.

So e.g. the following work as intended:
- https://arxiv.org/abs/2206.03509
- https://arxiv.org/abs/2111.00017

These older papers, with a different URL style fail:
- https://arxiv.org/abs/gr-qc/0210094
- https://arxiv.org/abs/hep-th/0608210

I.e. I don't even see the `Contacting host: arxiv.org:443` line in the `*Messages*` buffer.


However these older ones seem to work, i.e. the pdf is correctly downloaded:

- https://arxiv.org/abs/quant-ph/9612034v1
- https://arxiv.org/abs/hep-th/0106109


Regarding `org-protocol`, I think my problem was not having `zotra-download-attachment-for-current-entry` in the `zotra-after-add-entry-hook` list. When I add it, and ensure it's the last hook, this replicates the above behavior -- working on all the arXiv pages that worked above, and failing on the remainder.

**Comment by mpedramfar** [comment]
I see now! The issue was that `bibtex-clean-entry` was raising an error for those arxiv links and that resulted in not running the remaining hooks. The issue should be fixed now.

**Comment by deen1** [comment]
Thanks! I think that fixes it for me too -- at least the examples I mentioned above now work. Wasn't sure if I had to change `zotra-after-get-bibtex-entry-hook` but I guess you've aliased it to `zotra-after-add-entry-hook`. Fantastic! A very nice tool for Emacs.
