### ISSUE TITLE
Unsupported Media Type

### ISSUE THREAD

**Issue by tshu-w** [mpedramfar/zotra#7]
I got "Unsupported Media Type" if I use `curl_translation-server` backend.
Here are the args of `call-process` in `zotra-run-external-command`:
```
("curl" nil (#<buffer  *temp*> "/var/folders/fy/8scfs8vs1tj20n2dwyqyv_6c0000gn/T/zotra-stderr-Nm6K9z") nil "--max-time" "3" "-s" "--show-error" "-d" "https://arxiv.org/abs/2301.11305" "-H" "'Content-Type: text/plain'" "http://127.0.0.1:1969")
```
However, If I run this command in the terminal or use the `translation-server` backend, everything works fine.

GNU Emacs 29.0.60 (build 1, aarch64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2 (Build 22D49)) of 2023-01-28

**Comment by mpedramfar** [comment]
The last commit should fix the issue.
